docs: README updates [DEV-1187]
cheqd/infra pull request #23
Opened 2022-06-13 08:59 UTC by nikola-cheqd

2022-06-28 10:53 UTC, jay-dee7 commented on terragrunt/mainnet/hetzner/terragrunt.hcl
> +  source = "git::https://github.com/cheqd/cheqd-infra.git//terraform/hetzner?ref=${include.root.inputs.tag}"
@nikola-cheqd we can update this path to use `github.com/cheqd/infra` instead of `cheqd-infra`?

2022-06-28 10:53 UTC, jay-dee7 commented on terragrunt/mainnet/digital-ocean/terragrunt.hcl
> +  source = "git::https://github.com/cheqd/cheqd-infra.git//terraform/digital-ocean?ref=${include.root.inputs.tag}"
update Github link to use `infra` instead of `cheqd-infra` @nikola-cheqd

2022-06-28 10:54 UTC, jay-dee7 commented on terragrunt/terragrunt.hcl
> +    bucket                      = "cheqd-terraform-state-bucket"
@nikola-cheqd we can redact this one, so that we don't cause any confusion

2022-06-28 10:56 UTC, jay-dee7 requested changes
@nikola-cheqd just tiny changes are required before merging this one in. Please take a look at the comments :)

2022-06-28 11:18 UTC, jay-dee7 approved these changes
LGTM 🥇 🥇 🥇

2022-07-05 01:00 UTC, ankurdotb approved these changes

2022-07-05 01:31 UTC, merged